CREATE TABLE IF NOT EXISTS users
(
    id       INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login    VARCHAR(20) UNIQUE                   NOT NULL,
    password TEXT                                 NOT NULL,
    CONSTRAINT pk_user_id PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS tasks
(
    id          INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        TEXT                                 NOT NULL,
    description TEXT,
    dateTime    TIMESTAMP,
    CONSTRAINT pk_task_id primary key (id)
);

/*CREATE TABLE IF NOT EXISTS users_tasks
(
    id_user INT NOT NULL,
    id_task INT NOT NULL,
    CONSTRAINT fk_user_id FOREIGN KEY (id_user) REFERENCES users (id),
    CONSTRAINT fk_task_id FOREIGN KEY (id_task) REFERENCES tasks (id)
);
*/